### ISSUE TITLE
Final proofreading

### ISSUE THREAD

**Issue by pneuvial** [computorg/published-202311-delattre-fim#4]
Dear @madelattre,

The final version of your paper is now available at https://computo.sfds.asso.fr/published-202311-delattre-fim/

Can you make a final proofreading to ensure that everything is correct from your point of view ?

If any changes are needed, please fork this repository, make the required changes, and submit a pull request to this repository.

Thanks!

**Comment by madelattre** [comment]
Dear @pneuvial,
Thank you for the final version. 
We have nothing to report following the latest proofreading. 
This version can be kept as is.  
Best regards.
